var res = [ { marketId: '1.109919717',
    marketName: 'Match Odds',
    description: 
     { persistenceEnabled: true,
       bspMarket: false,
       marketTime: '2013-07-01T10:30:00.000Z',
       suspendTime: '2013-07-01T10:30:00.000Z',
       bettingType: 'ODDS',
       turnInPlayEnabled: true,
       marketType: 'MATCH_ODDS',
       marketBaseRate: 5,
       discountAllowed: true,
       wallet: 'UK wallet',
       rules: '<b>MARKET INFORMATION</b><br><br>For further information please see <a href=http://content.betfair.com/aboutus/content.asp?sWhichKey=Rules%20and%20Regulations#undefined.do style=color:0163ad; text-decoration: underline; target=_blank>Rules & Regs</a>.<br><br>Who will win this match? At the start of play all unmatched bets will be cancelled and this market will be turned in-play. This market will not be actively managed therefore it is the responsibility of all users to manage their positions. <b><br><br>Customers should be aware that:<br><br>\n<li>Transmissions described as â€œliveâ€? by some broadcasters may actually be delayed and that all in-play matches are not necessarily televised.</li><br><li>The extent of any such delay may vary, depending on the set-up through which they are receiving pictures or data.</li><br><br></b><b><FONT COLOR=\'red\'> If the first set is not completed all bets on this market will be void.</FONT></b><br><br>Please be aware that times may be subject to change.<br><br><A HREF="http://form.tennis.betfair.com/tennis" target="_blank"><b><FONT COLOUR=â€™redâ€™>New Tennis Betting Zone</FONT></b></A><br>',
       rulesHasDate: true },
    runners: [ [Object], [Object] ],
    eventType: { id: '2', name: 'Tennis' },
    event: 
     { id: '27029410',
       name: 'Seppi v Del Potro',
       countryCode: 'GB',
       timezone: 'Europe/London',
       openDate: '2013-07-01T10:30:00.000Z' } },
  { marketId: '1.109919729',
    marketName: 'Seppi To Win A Set?',
    description: 
     { persistenceEnabled: true,
       bspMarket: false,
       marketTime: '2013-07-01T10:30:00.000Z',
       suspendTime: '2013-07-01T10:30:00.000Z',
       bettingType: 'ODDS',
       turnInPlayEnabled: true,
       marketBaseRate: 5,
       discountAllowed: false,
       wallet: 'UK wallet',
       rules: '<b>Market Information</b><br>For further information please see <a href=http://content.betfair.com/aboutus/content.asp?sWhichKey=Rules%20and%20Regulations#undefined.do style=color:0163ad; text-decoration: underline; target=_blank>Rules & Regs</a>.<br><br> Will the named player win a set in this best of five set match? At the start of play all unmatched bets will be cancelled and this market will be turned in-play. This market will not be actively managed therefore it is the responsibility of all users to manage their positions. If either player retires before the completion of the third set all bets will be void, unless the result to this market has already been determined. <br><b><br>Customers should be aware that:<br><br><li>Transmissions described as â€œliveâ€? by some broadcasters may actually be delayed and that all in-play matches are not necessarily televised.</li><br><li>The extent of any such delay may vary, depending on the set-up through which they are receiving pictures or data.</li><br><br></b>',
       rulesHasDate: false },
    runners: [ [Object], [Object] ],
    eventType: { id: '2', name: 'Tennis' },
    event: 
     { id: '27029410',
       name: 'Seppi v Del Potro',
       countryCode: 'GB',
       timezone: 'Europe/London',
       openDate: '2013-07-01T10:30:00.000Z' } },
  { marketId: '1.109919730',
    marketName: 'Del Potro To Win A Set?',
    description: 
     { persistenceEnabled: true,
       bspMarket: false,
       marketTime: '2013-07-01T10:30:00.000Z',
       suspendTime: '2013-07-01T10:30:00.000Z',
       bettingType: 'ODDS',
       turnInPlayEnabled: true,
       marketBaseRate: 5,
       discountAllowed: false,
       wallet: 'UK wallet',
       rules: '<b>Market Information</b><br>For further information please see <a href=http://content.betfair.com/aboutus/content.asp?sWhichKey=Rules%20and%20Regulations#undefined.do style=color:0163ad; text-decoration: underline; target=_blank>Rules & Regs</a>.<br><br> Will the named player win a set in this best of five set match? At the start of play all unmatched bets will be cancelled and this market will be turned in-play. This market will not be actively managed therefore it is the responsibility of all users to manage their positions. If either player retires before the completion of the third set all bets will be void, unless the result to this market has already been determined. <br><b><br>Customers should be aware that:<br><br><li>Transmissions described as â€œliveâ€? by some broadcasters may actually be delayed and that all in-play matches are not necessarily televised.</li><br><li>The extent of any such delay may vary, depending on the set-up through which they are receiving pictures or data.</li><br><br></b>',
       rulesHasDate: true },
    runners: [ [Object], [Object] ],
    eventType: { id: '2', name: 'Tennis' },
    event: 
     { id: '27029410',
       name: 'Seppi v Del Potro',
       countryCode: 'GB',
       timezone: 'Europe/London',
       openDate: '2013-07-01T10:30:00.000Z' } },
  { marketId: '1.109919727',
    marketName: 'Set 04 Winner',
    description: 
     { persistenceEnabled: true,
       bspMarket: false,
       marketTime: '2013-07-01T10:30:00.000Z',
       suspendTime: '2013-07-01T10:30:00.000Z',
       bettingType: 'ODDS',
       turnInPlayEnabled: true,
       marketType: 'SET_WINNER',
       marketBaseRate: 5,
       discountAllowed: false,
       wallet: 'UK wallet',
       rules: '<b>Market Information</b><br>For further information please see <a href=http://content.betfair.com/aboutus/content.asp?sWhichKey=Rules%20and%20Regulations#undefined.do style=color:0163ad; text-decoration: underline; target=_blank>Rules & Regs</a>.<br><br> Who will win the stated set in this match? At the start of play all unmatched bets will be cancelled and this market will be turned in-play. This market will not be actively managed therefore it is the responsibility of all users to manage their positions. If the stated set is not completed all bets on this market will be void. <br><b><br>Customers should be aware that:<br><br>\n<li>Transmissions described as â€œliveâ€? by some broadcasters may actually be delayed and that all in-play matches are not necessarily televised.</li><br><li>The extent of any such delay may vary, depending on the set-up through which they are receiving pictures or data.</li><br><br></b>',
       rulesHasDate: true },
    runners: [ [Object], [Object] ],
    eventType: { id: '2', name: 'Tennis' },
    event: 
     { id: '27029410',
       name: 'Seppi v Del Potro',
       countryCode: 'GB',
       timezone: 'Europe/London',
       openDate: '2013-07-01T10:30:00.000Z' } },
  { marketId: '1.109919728',
    marketName: 'Number of Sets?',
    description: 
     { persistenceEnabled: true,
       bspMarket: false,
       marketTime: '2013-07-01T10:30:00.000Z',
       suspendTime: '2013-07-01T10:30:00.000Z',
       bettingType: 'ODDS',
       turnInPlayEnabled: true,
       marketBaseRate: 5,
       discountAllowed: false,
       wallet: 'UK wallet',
       rules: '<b>Market Information</b><br>For further information please see <a href=http://content.betfair.com/aboutus/content.asp?sWhichKey=Rules%20and%20Regulations#undefined.do style=color:0163ad; text-decoration: underline; target=_blank>Rules & Regs</a>.<br><br>How many sets will be played in this match? At the start of play unmatched bets will be cancelled and this market will be turned in play. At no point during the match will Betfair cancel unmatched bets. This market will not be actively managed therefore, it is the responsibility of all users to manage their in-play positions.<b><br><br>Customers should be aware that:<br><br><li>Transmissions described as â€œliveâ€? by some broadcasters may actually be delayed and that all in-play matches are not necessarily televised.</li><br><li>The extent of any such delay may vary, depending on the set-up through which they are receiving pictures or data.</li><br><br></b><b><FONT COLOR=\'red\'> If a retirement occurs before the completion of the fourth set this market will be void.  If a retirement occurs after the completion of the fourth set the market will be settled as FIVE SETS.</FONT></b><br><br>Please be aware that times may be subject to change.\n',
       rulesHasDate: true },
    runners: [ [Object], [Object], [Object] ],
    eventType: { id: '2', name: 'Tennis' },
    event: 
     { id: '27029410',
       name: 'Seppi v Del Potro',
       countryCode: 'GB',
       timezone: 'Europe/London',
       openDate: '2013-07-01T10:30:00.000Z' } },
  { marketId: '1.109919724',
    marketName: 'Set 02 Winner',
    description: 
     { persistenceEnabled: true,
       bspMarket: false,
       marketTime: '2013-07-01T10:30:00.000Z',
       suspendTime: '2013-07-01T10:30:00.000Z',
       bettingType: 'ODDS',
       turnInPlayEnabled: true,
       marketType: 'SET_WINNER',
       marketBaseRate: 5,
       discountAllowed: false,
       wallet: 'UK wallet',
       rules: '<b>Market Information</b><br>For further information please see <a href=http://content.betfair.com/aboutus/content.asp?sWhichKey=Rules%20and%20Regulations#undefined.do style=color:0163ad; text-decoration: underline; target=_blank>Rules & Regs</a>.<br><br> Who will win the stated set in this match? At the start of play all unmatched bets will be cancelled and this market will be turned in-play. This market will not be actively managed therefore it is the responsibility of all users to manage their positions. If the stated set is not completed all bets on this market will be void. <br><b><br>Customers should be aware that:<br><br>\n<li>Transmissions described as â€œliveâ€? by some broadcasters may actually be delayed and that all in-play matches are not necessarily televised.</li><br><li>The extent of any such delay may vary, depending on the set-up through which they are receiving pictures or data.</li><br><br></b>',
       rulesHasDate: true },
    runners: [ [Object], [Object] ],
    eventType: { id: '2', name: 'Tennis' },
    event: 
     { id: '27029410',
       name: 'Seppi v Del Potro',
       countryCode: 'GB',
       timezone: 'Europe/London',
       openDate: '2013-07-01T10:30:00.000Z' } },
  { marketId: '1.109919723',
    marketName: 'Tie Break Played?',
    description: 
     { persistenceEnabled: true,
       bspMarket: false,
       marketTime: '2013-07-01T10:30:00.000Z',
       suspendTime: '2013-07-01T10:30:00.000Z',
       bettingType: 'ODDS',
       turnInPlayEnabled: true,
       marketType: 'TIE_BREAK',
       marketBaseRate: 5,
       discountAllowed: false,
       wallet: 'UK wallet',
       rules: '<b>Market Information</b><br>For further information please see <a href=http://content.betfair.com/aboutus/content.asp?sWhichKey=Rules%20and%20Regulations#undefined.do style=color:0163ad; text-decoration: underline; target=_blank>Rules & Regs</a>.<br><br>Will there be a tie break in this match? At the start of play all unmatched bets will be cancelled and this market will be turned in play. At no point during the match will Betfair cancel unmatched bets. This market will not be actively managed therefore, it is the responsibility of all users to manage their in-play positions.<b><br><br>Customers should be aware that:<br><br><li>Transmissions described as â€œliveâ€? by some broadcasters may actually be delayed and that all in-play matches are not necessarily televised.</li><br><li>The extent of any such delay may vary, depending on the set-up through which they are receiving pictures or data.</li><br><br></b><b><FONT COLOR=\'red\'>If a player retires before the completion of the match all bets will be void unless the market has been unconditionally determined.  For the purposes of this market if a player retires with the set score at six games all in any set in which a tie break could be played, or retires during a tie break the market will be settled as YES.</FONT></b><br><br>Please be aware that times may be subject to change.\n',
       rulesHasDate: true },
    runners: [ [Object], [Object] ],
    eventType: { id: '2', name: 'Tennis' },
    event: 
     { id: '27029410',
       name: 'Seppi v Del Potro',
       countryCode: 'GB',
       timezone: 'Europe/London',
       openDate: '2013-07-01T10:30:00.000Z' } },
  { marketId: '1.109919726',
    marketName: '6-0 Set?',
    description: 
     { persistenceEnabled: true,
       bspMarket: false,
       marketTime: '2013-07-01T10:30:00.000Z',
       suspendTime: '2013-07-01T10:30:00.000Z',
       bettingType: 'ODDS',
       turnInPlayEnabled: true,
       marketType: '6-0_SET',
       marketBaseRate: 5,
       discountAllowed: false,
       wallet: 'UK wallet',
       rules: '<b>Market Information</b><br>For further information please see <a href=http://content.betfair.com/aboutus/content.asp?sWhichKey=Rules%20and%20Regulations#undefined.do style=color:0163ad; text-decoration: underline; target=_blank>Rules & Regs</a>.<br><br> Will either player win a set by a 6-0 scoreline during this match? At the start of play all unmatched bets will be cancelled and this market will be turned in-play. This market will not be actively managed therefore it is the responsibility of all users to manage their positions. If a player retires before the completion of the match all bets will be void, unless the result to this market has already been determined.<br><b><br>Customers should be aware that:<br><br>\n<li>Transmissions described as â€œliveâ€? by some broadcasters may actually be delayed and that all in-play matches are not necessarily televised.</li><br><li>The extent of any such delay may vary, depending on the set-up through which they are receiving pictures or data.</li><br><br></b>',
       rulesHasDate: true },
    runners: [ [Object], [Object] ],
    eventType: { id: '2', name: 'Tennis' },
    event: 
     { id: '27029410',
       name: 'Seppi v Del Potro',
       countryCode: 'GB',
       timezone: 'Europe/London',
       openDate: '2013-07-01T10:30:00.000Z' } },
  { marketId: '1.109919725',
    marketName: 'Set 03 Winner',
    description: 
     { persistenceEnabled: true,
       bspMarket: false,
       marketTime: '2013-07-01T10:30:00.000Z',
       suspendTime: '2013-07-01T10:30:00.000Z',
       bettingType: 'ODDS',
       turnInPlayEnabled: true,
       marketType: 'SET_WINNER',
       marketBaseRate: 5,
       discountAllowed: false,
       wallet: 'UK wallet',
       rules: '<b>Market Information</b><br>For further information please see <a href=http://content.betfair.com/aboutus/content.asp?sWhichKey=Rules%20and%20Regulations#undefined.do style=color:0163ad; text-decoration: underline; target=_blank>Rules & Regs</a>.<br><br> Who will win the stated set in this match? At the start of play all unmatched bets will be cancelled and this market will be turned in-play. This market will not be actively managed therefore it is the responsibility of all users to manage their positions. If the stated set is not completed all bets on this market will be void. <br><b><br>Customers should be aware that:<br><br>\n<li>Transmissions described as â€œliveâ€? by some broadcasters may actually be delayed and that all in-play matches are not necessarily televised.</li><br><li>The extent of any such delay may vary, depending on the set-up through which they are receiving pictures or data.</li><br><br></b>',
       rulesHasDate: true },
    runners: [ [Object], [Object] ],
    eventType: { id: '2', name: 'Tennis' },
    event: 
     { id: '27029410',
       name: 'Seppi v Del Potro',
       countryCode: 'GB',
       timezone: 'Europe/London',
       openDate: '2013-07-01T10:30:00.000Z' } },
  { marketId: '1.109919719',
    marketName: 'Set 01 Winner',
    description: 
     { persistenceEnabled: true,
       bspMarket: false,
       marketTime: '2013-07-01T10:30:00.000Z',
       suspendTime: '2013-07-01T10:30:00.000Z',
       bettingType: 'ODDS',
       turnInPlayEnabled: true,
       marketType: 'SET_WINNER',
       marketBaseRate: 5,
       discountAllowed: false,
       wallet: 'UK wallet',
       rules: '<b>Market Information</b><br>For further information please see <a href=http://content.betfair.com/aboutus/content.asp?sWhichKey=Rules%20and%20Regulations#undefined.do style=color:0163ad; text-decoration: underline; target=_blank>Rules & Regs</a>.<br><br> Who will win the stated set in this match? At the start of play all unmatched bets will be cancelled and this market will be turned in-play. This market will not be actively managed therefore it is the responsibility of all users to manage their positions. If the stated set is not completed all bets on this market will be void. <br><b><br>Customers should be aware that:<br><br>\n<li>Transmissions described as â€œliveâ€? by some broadcasters may actually be delayed and that all in-play matches are not necessarily televised.</li><br><li>The extent of any such delay may vary, depending on the set-up through which they are receiving pictures or data.</li><br><br></b>',
       rulesHasDate: true },
    runners: [ [Object], [Object] ],
    eventType: { id: '2', name: 'Tennis' },
    event: 
     { id: '27029410',
       name: 'Seppi v Del Potro',
       countryCode: 'GB',
       timezone: 'Europe/London',
       openDate: '2013-07-01T10:30:00.000Z' } },
  { marketId: '1.109919718',
    marketName: 'Set Betting',
    description: 
     { persistenceEnabled: true,
       bspMarket: false,
       marketTime: '2013-07-01T10:30:00.000Z',
       suspendTime: '2013-07-01T10:30:00.000Z',
       bettingType: 'ODDS',
       turnInPlayEnabled: true,
       marketType: 'SET_BETTING',
       marketBaseRate: 5,
       discountAllowed: false,
       wallet: 'UK wallet',
       rules: '<b>MARKET INFORMATION</b><br><br>For further information please see <a href=http://content.betfair.com/aboutus/content.asp?sWhichKey=Rules%20and%20Regulations#undefined.do style=color:0163ad; text-decoration: underline; target=_blank>Rules & Regs</a>.<br><br> What will be the set score in this match?  At the start of play all unmatched bets will be cancelled and this market will be turned in-play. This market will not be actively managed therefore it is the responsibility of all users to manage their in-play positions.<br><br>Customers should be aware that:<br><br>\n<li><b>Transmissions described as â€œliveâ€? by some broadcasters may actually be delayed and that all in-play matches are not necessarily televised.</li><br><li>The extent of any such delay may vary, depending on the set-up through which they are receiving pictures or data.</li><br></b><b><FONT COLOR=\'red\'>If a player retires before the completion of the match all bets will be void.</FONT></b><br><br>Please be aware that times may be subject to change.<br><br><A HREF="http://form.tennis.betfair.com/tennis" target="_blank"><b><FONT COLOUR=â€™redâ€™>New Tennis Betting Zone</FONT></b></A><br>',
       rulesHasDate: true },
    runners: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    eventType: { id: '2', name: 'Tennis' },
    event: 
     { id: '27029410',
       name: 'Seppi v Del Potro',
       countryCode: 'GB',
       timezone: 'Europe/London',
       openDate: '2013-07-01T10:30:00.000Z' } },
  { marketId: '1.109919722',
    marketName: 'Set 01 - Correct Score',
    description: 
     { persistenceEnabled: true,
       bspMarket: false,
       marketTime: '2013-07-01T10:30:00.000Z',
       suspendTime: '2013-07-01T10:30:00.000Z',
       bettingType: 'ODDS',
       turnInPlayEnabled: true,
       marketType: 'SET_CORRECT_SCORE',
       marketBaseRate: 5,
       discountAllowed: false,
       wallet: 'UK wallet',
       rules: '<b>MARKET INFORMATION</b><br>For further information please see <a href=http://content.betfair.com/aboutus/content.asp?sWhichKey=Rules%20and%20Regulations#undefined.do style=color:0163ad; text-decoration: underline; target=_blank>Rules & Regs</a>.<br><br>What will be the correct score in the first set of this match? At the start of play all unmatched bets will be cancelled and this market will be turned in play. This market will not be actively managed therefore it is the responsibility of all users to manage their in-play positions. <br><br>Customers should be aware that:<br><br>\n<li>Transmissions described as â€œliveâ€? by some broadcasters may actually be delayed and that all in-play matches are not necessarily televised.</li><br><li>The extent of any such delay may vary, depending on the set-up through which they are receiving pictures or data.</li><br><br><b/><FONT COLOR=\'red\'>If a player retires before the completion of the first set all bets will be void.</FONT></b><br><br>Please be aware that times may be subject to change.<br><br><A HREF="http://form.tennis.betfair.com/tennis" target="_blank"><b><FONT COLOUR=â€™redâ€™>New Tennis Betting Zone</FONT></b></A><br>',
       rulesHasDate: true },
    runners: 
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    eventType: { id: '2', name: 'Tennis' },
    event: 
     { id: '27029410',
       name: 'Seppi v Del Potro',
       countryCode: 'GB',
       timezone: 'Europe/London',
       openDate: '2013-07-01T10:30:00.000Z' } } ]
       
       
       
     var types = ['SET_WINNER', 'MATCH_ODDS', 'ODDS']
 	
 var _ = require('underscore'); 	
 	


/**
* Removes object attributes without a name containing 
* a player key word.
*/ 
resf = _.filter(res, function(obj) {
		var ret;
		
		for(var i in types) {
			ret = ret || obj.description.marketType == undefined ? 0 : ~obj.description.marketType.toLowerCase().indexOf(types[i].toLowerCase()); 
		}
		return ret;
});

console.log(resf); 
